import imageCompression from 'browser-image-compression';
import { CompressionOptions, ImageConversionOptions, ResizeOptions, CropOptions } from '@/types/file';

export async function compressImage(
  file: File,
    options: CompressionOptions,
      onProgress?: (progress: number) => void
      ): Promise<File> {
        const compressionOptions = {
            maxSizeMB: 1,
                maxWidthOrHeight: options.maxWidth || 1920,
                    useWebWorker: true,
                        quality: options.quality / 100,
                            fileType: options.fileType || file.type,
                                onProgress: (progress: number) => {
                                      onProgress?.(progress);
                                          },
                                            };

                                              try {
                                                  const compressedFile = await imageCompression(file, compressionOptions);
                                                      return compressedFile;
                                                        } catch (error) {
                                                            console.error('Image compression failed:', error);
                                                                throw new Error('Failed to compress image');
                                                                  }
                                                                  }

                                                                  export async function convertImage(
                                                                    file: File,
                                                                      options: ImageConversionOptions,
                                                                        onProgress?: (progress: number) => void
                                                                        ): Promise<Blob> {
                                                                          return new Promise((resolve, reject) => {
                                                                              const img = new Image();
                                                                                  const canvas = document.createElement('canvas');
                                                                                      const ctx = canvas.getContext('2d');

                                                                                          img.onload = () => {
                                                                                                canvas.width = img.width;
                                                                                                      canvas.height = img.height;
                                                                                                            
                                                                                                                  if (ctx) {
                                                                                                                          ctx.drawImage(img, 0, 0);
                                                                                                                                  
                                                                                                                                          canvas.toBlob(
                                                                                                                                                    (blob) => {
                                                                                                                                                                if (blob) {
                                                                                                                                                                              onProgress?.(100);
                                                                                                                                                                                            resolve(blob);
                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                      reject(new Error('Failed to convert image'));
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                      `image/${options.targetFormat}`,
                                                                                                                                                                                                                                                                options.quality ? options.quality / 100 : 0.92
                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                  };

                                                                                                                                                                                                                                                                                      img.onerror = () => reject(new Error('Failed to load image'));
                                                                                                                                                                                                                                                                                          img.src = URL.createObjectURL(file);
                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                            export async function resizeImage(
                                                                                                                                                                                                                                                                                              file: File,
                                                                                                                                                                                                                                                                                                options: ResizeOptions,
                                                                                                                                                                                                                                                                                                  onProgress?: (progress: number) => void
                                                                                                                                                                                                                                                                                                  ): Promise<Blob> {
                                                                                                                                                                                                                                                                                                    return new Promise((resolve, reject) => {
                                                                                                                                                                                                                                                                                                        const img = new Image();
                                                                                                                                                                                                                                                                                                            const canvas = document.createElement('canvas');
                                                                                                                                                                                                                                                                                                                const ctx = canvas.getContext('2d');

                                                                                                                                                                                                                                                                                                                    img.onload = () => {
                                                                                                                                                                                                                                                                                                                          let { width, height } = options;

                                                                                                                                                                                                                                                                                                                                if (options.maintainAspectRatio) {
                                                                                                                                                                                                                                                                                                                                        if (width && height) {
                                                                                                                                                                                                                                                                                                                                                  const ratio = Math.min(width / img.width, height / img.height);
                                                                                                                                                                                                                                                                                                                                                            width = img.width * ratio;
                                                                                                                                                                                                                                                                                                                                                                      height = img.height * ratio;
                                                                                                                                                                                                                                                                                                                                                                              } else if (width) {
                                                                                                                                                                                                                                                                                                                                                                                        height = (img.height * width) / img.width;
                                                                                                                                                                                                                                                                                                                                                                                                } else if (height) {
                                                                                                                                                                                                                                                                                                                                                                                                          width = (img.width * height) / img.height;
                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                              canvas.width = width || img.width;
                                                                                                                                                                                                                                                                                                                                                                                                                                    canvas.height = height || img.height;

                                                                                                                                                                                                                                                                                                                                                                                                                                          if (ctx) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  canvas.toBlob(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            (blob) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (blob) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onProgress?.(100);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    resolve(blob);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              reject(new Error('Failed to resize image'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              file.type,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        0.92
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              img.onerror = () => reject(new Error('Failed to load image'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onProgress?.(25);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      img.src = URL.createObjectURL(file);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export async function cropImage(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          file: File,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            options: CropOptions,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onProgress?: (progress: number) => void
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ): Promise<Blob> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return new Promise((resolve, reject) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const img = new Image();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const canvas = document.createElement('canvas');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const ctx = canvas.getContext('2d');

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                img.onload = () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      canvas.width = options.width;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            canvas.height = options.height;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (ctx) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ctx.drawImage(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    img,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              options.x,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        options.y,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  options.width,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            options.height,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                0,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          options.width,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    options.height
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    canvas.toBlob(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              (blob) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (blob) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onProgress?.(100);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      resolve(blob);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                reject(new Error('Failed to crop image'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                file.type,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          0.92
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                img.onerror = () => reject(new Error('Failed to load image'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onProgress?.(25);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        img.src = URL.createObjectURL(file);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export async function createImagePreview(file: File): Promise<string> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return new Promise((resolve, reject) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const reader = new FileReader();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    reader.onload = () => resolve(reader.result as string);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        reader.onerror = () => reject(new Error('Failed to create preview'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            reader.readAsDataURL(file);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export function getImageDimensions(file: File): Promise<{ width: number; height: number }> {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return new Promise((resolve, reject) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const img = new Image();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        img.onload = () => resolve({ width: img.width, height: img.height });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            img.onerror = () => reject(new Error('Failed to get image dimensions'));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                img.src = URL.createObjectURL(file);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }