/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
      serverActions: {
            bodySizeLimit: '50mb',
                },
                  },
                    async headers() {
                        return [
                              {
                                      source: '/:path*',
                                              headers: [
                                                        {
                                                                    key: 'X-DNS-Prefetch-Control',
                                                                                value: 'on',
                                                                                          },
                                                                                                    {
                                                                                                                key: 'X-XSS-Protection',
                                                                                                                            value: '1; mode=block',
                                                                                                                                      },
                                                                                                                                                {
                                                                                                                                                            key: 'X-Frame-Options',
                                                                                                                                                                        value: 'SAMEORIGIN',
                                                                                                                                                                                  },
                                                                                                                                                                                            {
                                                                                                                                                                                                        key: 'X-Content-Type-Options',
                                                                                                                                                                                                                    value: 'nosniff',
                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                    key: 'Referrer-Policy',
                                                                                                                                                                                                                                                                value: 'strict-origin-when-cross-origin',
                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                key: 'Permissions-Policy',
                                                                                                                                                                                                                                                                                                            value: 'camera=(), microphone=(), geolocation=()',
                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                              ],
                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                        ];
                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                            webpack: (config, { isServer }) => {
                                                                                                                                                                                                                                                                                                                                                if (!isServer) {
                                                                                                                                                                                                                                                                                                                                                      config.resolve.fallback = {
                                                                                                                                                                                                                                                                                                                                                              ...config.resolve.fallback,
                                                                                                                                                                                                                                                                                                                                                                      fs: false,
                                                                                                                                                                                                                                                                                                                                                                              path: false,
                                                                                                                                                                                                                                                                                                                                                                                      crypto: false,
                                                                                                                                                                                                                                                                                                                                                                                            };
                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                    return config;
                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                      module.exports = nextConfig; */