'use client';

import React, { useState, useCallback } from 'react';
import { DropZone } from '@/components/ui/DropZone';
import { FileList } from '@/components/ui/FileList';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { ProgressBar } from '@/components/ui/ProgressBar';
import { useFileProcessing } from '@/hooks/useFileProcessing';
import { useCompressionHistory } from '@/hooks/useCompressionHistory';
import { useToast } from '@/hooks/useToast';
import { convertImage, createImagePreview } from '@/lib/image-processing';
import { downloadBlob } from '@/lib/utils';
import { Repeat, Download } from 'lucide-react';

const FORMATS = [
  { value: 'jpeg', label: 'JPG', ext: 'jpg' },
    { value: 'png', label: 'PNG', ext: 'png' },
      { value: 'webp', label: 'WebP', ext: 'webp' },
        { value: 'avif', label: 'AVIF', ext: 'avif' },
        ] as const;

        export function ImageConverter() {
          const [targetFormat, setTargetFormat] = useState<string>('webp');
            const [quality, setQuality] = useState(90);
              const { addToHistory } = useCompressionHistory();
                const { showSuccess, showError } = useToast();
                  const {
                      files,
                          addFiles,
                              removeFile,
                                  clearFiles,
                                      processFiles,
                                          isProcessing,
                                            } = useFileProcessing({
                                                maxFiles: 20,
                                                    maxSize: 50 * 1024 * 1024,
                                                        acceptedTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/avif'],
                                                          });

                                                            const handleConvert = useCallback(async () => {
                                                                const ext = FORMATS.find((f) => f.value === targetFormat)?.ext || 'jpg';

                                                                    const convert = async (fileWithMeta: typeof files[0]) => {
                                                                          const converted = await convertImage(fileWithMeta.file, {
                                                                                  targetFormat: targetFormat as 'jpeg' | 'png' | 'webp' | 'avif',
                                                                                          quality,
                                                                                                });
                                                                                                      const newName = fileWithMeta.name.replace(/\.[^.]+$/, `.${ext}`);
                                                                                                            const preview = await createImagePreview(new File([converted], newName));
                                                                                                                  return {
                                                                                                                          ...fileWithMeta,
                                                                                                                                  processedFile: converted,
                                                                                                                                          processedSize: converted.size,
                                                                                                                                                  preview,
                                                                                                                                                          status: 'completed' as const,
                                                                                                                                                                };
                                                                                                                                                                    };

                                                                                                                                                                        await processFiles(convert);
                                                                                                                                                                            addToHistory({
                                                                                                                                                                                  toolId: 'image-converter',
                                                                                                                                                                                        toolName: 'Image Converter',
                                                                                                                                                                                              filesProcessed: files.length,
                                                                                                                                                                                                    spaceSaved: 0,
                                                                                                                                                                                                          timestamp: Date.now(),
                                                                                                                                                                                                              });
                                                                                                                                                                                                                  showSuccess(`Converted ${files.length} file(s) to ${targetFormat.toUpperCase()}`);
                                                                                                                                                                                                                    }, [files, targetFormat, quality, processFiles, addToHistory, showSuccess]);

                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                          <div className="space-y-6">
                                                                                                                                                                                                                                <Card>
                                                                                                                                                                                                                                        <h3 className="font-semibold text-gray-900 dark:text-white mb-4">Format</h3>
                                                                                                                                                                                                                                                <div className="grid grid-cols-2 gap-2 mb-4">
                                                                                                                                                                                                                                                          {FORMATS.map((f) => (
                                                                                                                                                                                                                                                                      <Button
                                                                                                                                                                                                                                                                                    key={f.value}
                                                                                                                                                                                                                                                                                                  variant={targetFormat === f.value ? 'primary' : 'ghost'}
                                                                                                                                                                                                                                                                                                                size="sm"
                                                                                                                                                                                                                                                                                                                              onClick={() => setTargetFormat(f.value)}
                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                        {f.label}
                                                                                                                                                                                                                                                                                                                                                                    </Button>
                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                              <label className="text-sm font-medium">Quality: {quality}%</label>
                                                                                                                                                                                                                                                                                                                                                                                                      <input
                                                                                                                                                                                                                                                                                                                                                                                                                type="range"
                                                                                                                                                                                                                                                                                                                                                                                                                          min="1"
                                                                                                                                                                                                                                                                                                                                                                                                                                    max="100"
                                                                                                                                                                                                                                                                                                                                                                                                                                              value={quality}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChange={(e) => setQuality(parseInt(e.target.value))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="w-full"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <DropZone
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onFilesSelected={addFiles}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      acceptedTypes={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'image/jpeg': ['.jpg'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          'image/png': ['.png'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'image/webp': ['.webp'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'image/avif': ['.avif'],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              maxFiles={20}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <FileList files={files} onRemove={removeFile} onClear={clearFiles} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {isProcessing && <ProgressBar indeterminate label="Converting..." />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {files.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex gap-3 justify-end">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Button onClick={handleConvert} loading={isProcessing} icon={<Repeat className="w-5 h-5" />}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Convert {files.length} File{files.length !== 1 ? 's' : ''}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {files.some((f) => f.processedFile) && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Button variant="secondary" onClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const ext = FORMATS.find((f) => f.value === targetFormat)?.ext || 'jpg';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                files.filter((f) => f.processedFile).forEach((f) =>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                downloadBlob(f.processedFile!, f.name.replace(/\.[^.]+$/, `.${ext}`))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }} icon={<Download className="w-5 h-5" />}>Download All</Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }