'use client';

import Link from 'next/link';
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/Button';
import { FileQuestion, Home } from 'lucide-react';

export default function NotFound() {
  return (
      <div className="min-h-[80vh] flex items-center justify-center px-4">
            <motion.div
                    initial={{ opacity: 0, scale: 0.9 }}
                            animate={{ opacity: 1, scale: 1 }}
                                    transition={{ duration: 0.5 }}
                                            className="text-center"
                                                  >
                                                          <motion.div
                                                                    animate={{
                                                                                rotate: [0, 10, -10, 0],
                                                                                          }}
                                                                                                    transition={{
                                                                                                                duration: 2,
                                                                                                                            repeat: Infinity,
                                                                                                                                        repeatType: "reverse",
                                                                                                                                                  }}
                                                                                                                                                            className="inline-block mb-8"
                                                                                                                                                                    >
                                                                                                                                                                              <FileQuestion className="w-24 h-24 text-primary-500" />
                                                                                                                                                                                      </motion.div>
                                                                                                                                                                                              
                                                                                                                                                                                                      <h1 className="text-6xl font-bold text-gray-900 dark:text-white mb-4">
                                                                                                                                                                                                                404
                                                                                                                                                                                                                        </h1>
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                        <h2 className="text-2xl font-semibold text-gray-700 dark:text-gray-300 mb-4">
                                                                                                                                                                                                                                                  Page Not Found
                                                                                                                                                                                                                                                          </h2>
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                          <p className="text-gray-500 dark:text-gray-400 mb-8 max-w-md mx-auto">
                                                                                                                                                                                                                                                                                    The page you're looking for doesn't exist or has been moved.
                                                                                                                                                                                                                                                                                              Let's get you back on track.
                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                      <div className="flex gap-4 justify-center">
                                                                                                                                                                                                                                                                                                                                <Link href="/">
                                                                                                                                                                                                                                                                                                                                            <Button icon={<Home className="w-5 h-5" />}>
                                                                                                                                                                                                                                                                                                                                                          Go Home
                                                                                                                                                                                                                                                                                                                                                                      </Button>
                                                                                                                                                                                                                                                                                                                                                                                </Link>
                                                                                                                                                                                                                                                                                                                                                                                          <Link href="/about">
                                                                                                                                                                                                                                                                                                                                                                                                      <Button variant="secondary">
                                                                                                                                                                                                                                                                                                                                                                                                                    Learn More
                                                                                                                                                                                                                                                                                                                                                                                                                                </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </motion.div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                              }