import { Tool } from '@/types/tools';

export const tools: Tool[] = [
    {
        id: 'image-compressor',
        name: 'Image Compressor',
        description: 'Compress images without losing quality. Supports JPG, PNG, WebP, and AVIF.',
        icon: 'ImageIcon',
        route: '/image-compressor',
        category: 'image',
        features: [
            'Batch compression',
            'Quality adjustment',
            'Lossless option',
            'Before/after preview',
            'Download as ZIP',
        ],
        acceptedTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/avif'],
        maxFileSize: 50 * 1024 * 1024, // 50MB
        maxFiles: 20,
    },
    {
        id: 'image-converter',
        name: 'Image Converter',
        description: 'Convert between JPG, PNG, WebP, and AVIF formats.',
        icon: 'Repeat',
        route: '/image-converter',
        category: 'converter',
        features: [
            'Multiple format support',
            'Quality control',
            'Batch conversion',
            'Preserve metadata',
        ],
        acceptedTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/avif'],
        maxFileSize: 50 * 1024 * 1024,
        maxFiles: 20,
    },
    {
        id: 'resize-image',
        name: 'Resize Image',
        description: 'Resize images to exact dimensions or percentage.',
        icon: 'Maximize2',
        route: '/resize-image',
        category: 'image',
        features: [
            'Exact dimensions',
            'Percentage scaling',
            'Maintain aspect ratio',
            'Custom presets',
        ],
        acceptedTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/avif'],
        maxFileSize: 50 * 1024 * 1024,
        maxFiles: 10,
    },
    {
        id: 'crop-image',
        name: 'Crop Image',
        description: 'Crop images with precise control and common aspect ratios.',
        icon: 'Crop',
        route: '/crop-image',
        category: 'image',
        features: [
            'Freeform crop',
            'Preset ratios',
            'Real-time preview',
            'Position adjustment',
        ],
        acceptedTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/avif'],
        maxFileSize: 50 * 1024 * 1024,
        maxFiles: 1,
    },
    {
        id: 'pdf-compressor',
        name: 'PDF Compressor',
        description: 'Reduce PDF file size while maintaining quality.',
        icon: 'FileDown',
        route: '/pdf-compressor',
        category: 'pdf',
        features: [
            'Quality levels',
            'Fast processing',
            'Secure processing',
            'Download directly',
        ],
        acceptedTypes: ['application/pdf'],
        maxFileSize: 100 * 1024 * 1024,
        maxFiles: 5,
    },
    {
        id: 'merge-pdf',
        name: 'Merge PDF',
        description: 'Combine multiple PDFs into a single document.',
        icon: 'Combine',
        route: '/merge-pdf',
        category: 'pdf',
        features: [
            'Reorder pages',
            'Multiple files',
            'Preview pages',
            'Fast merging',
        ],
        acceptedTypes: ['application/pdf'],
        maxFileSize: 100 * 1024 * 1024,
        maxFiles: 20,
    },
    {
        id: 'split-pdf',
        name: 'Split PDF',
        description: 'Split a PDF into multiple documents.',
        icon: 'Scissors',
        route: '/split-pdf',
        category: 'pdf',
        features: [
            'Split by range',
            'Extract pages',
            'Delete pages',
            'Bulk operations',
        ],
        acceptedTypes: ['application/pdf'],
        maxFileSize: 100 * 1024 * 1024,
        maxFiles: 1,
    },
    {
        id: 'jpg-to-pdf',
        name: 'JPG to PDF',
        description: 'Convert images to PDF documents.',
        icon: 'FileUp',
        route: '/jpg-to-pdf',
        category: 'converter',
        features: [
            'Multiple images',
            'Page ordering',
            'Custom page size',
            'Fast conversion',
        ],
        acceptedTypes: ['image/jpeg', 'image/png'],
        maxFileSize: 50 * 1024 * 1024,
        maxFiles: 20,
    },
    {
        id: 'pdf-to-jpg',
        name: 'PDF to JPG',
        description: 'Convert PDF pages to high-quality images.',
        icon: 'ImageIcon',
        route: '/pdf-to-jpg',
        category: 'converter',
        features: [
            'Page selection',
            'Quality settings',
            'Batch export',
            'High resolution',
        ],
        acceptedTypes: ['application/pdf'],
        maxFileSize: 100 * 1024 * 1024,
        maxFiles: 5,
    },
    {
        id: 'webp-converter',
        name: 'WebP Converter',
        description: 'Convert between WebP and other formats.',
        icon: 'Image',
        route: '/webp-converter',
        category: 'converter',
        features: [
            'Bidirectional conversion',
            'Quality control',
            'Batch processing',
            'Transparency support',
        ],
        acceptedTypes: ['image/jpeg', 'image/png', 'image/webp'],
        maxFileSize: 50 * 1024 * 1024,
        maxFiles: 20,
    },
];

export const toolCategories = [
    { id: 'all', label: 'All Tools' },
    { id: 'image', label: 'Image Tools' },
    { id: 'pdf', label: 'PDF Tools' },
    { id: 'converter', label: 'Converters' },
] as const;