'use client';

import React, { useState, useCallback } from 'react';
import { ToolLayout } from '@/components/ui/ToolLayout';
import { DropZone } from '@/components/ui/DropZone';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { ProgressBar } from '@/components/ui/ProgressBar';
import { useToast } from '@/hooks/useToast';
import { useCompressionHistory } from '@/hooks/useCompressionHistory';
import { pdfToImages } from '@/lib/pdf-processing';
import { downloadBlob } from '@/lib/utils';
import { FileImage, Download } from 'lucide-react';

      export default function PdfToJpgPage() {
        const [sourceFile, setSourceFile] = useState<File | null>(null);
          const [images, setImages] = useState<Blob[]>([]);
            const [isProcessing, setIsProcessing] = useState(false);

              const { addToHistory } = useCompressionHistory();
                const { showSuccess, showError } = useToast();

                  const handleFileSelect = useCallback((files: File[]) => {
                      if (files.length > 0) {
                            setSourceFile(files[0]);
                                  setImages([]);
                                      }
                                        }, []);

                                          const handleConvert = useCallback(async () => {
                                              if (!sourceFile) return;

                                                  setIsProcessing(true);
                                                      try {
                                                            const result = await pdfToImages(sourceFile, 'jpeg');
                                                                  setImages(result);

                                                                        addToHistory({
                                                                                toolId: 'pdf-to-jpg',
                                                                                        toolName: 'PDF to JPG',
                                                                                                filesProcessed: 1,
                                                                                                        spaceSaved: 0,
                                                                                                                timestamp: Date.now(),
                                                                                                                      });

                                                                                                                            showSuccess(`Converted ${result.length} page(s) to JPG`);
                                                                                                                                } catch (error) {
                                                                                                                                      showError('Failed to convert PDF to images');
                                                                                                                                          } finally {
                                                                                                                                                setIsProcessing(false);
                                                                                                                                                    }
                                                                                                                                                      }, [sourceFile, addToHistory, showSuccess, showError]);

                                                                                                                                                        const handleDownload = useCallback(
                                                                                                                                                            (blob: Blob, index: number) => {
                                                                                                                                                                  downloadBlob(blob, `page_${index + 1}.jpg`);
                                                                                                                                                                        showSuccess(`Downloaded page ${index + 1}`);
                                                                                                                                                                            },
                                                                                                                                                                                [showSuccess]
                                                                                                                                                                                  );

                                                                                                                                                                                    const handleDownloadAll = useCallback(() => {
                                                                                                                                                                                        images.forEach((blob, i) => downloadBlob(blob, `page_${i + 1}.jpg`));
                                                                                                                                                                                            showSuccess(`Downloaded ${images.length} image(s)`);
                                                                                                                                                                                              }, [images, showSuccess]);

                                                                                                                                                                                                return (
                                                                                                                                                                                                    <ToolLayout
                                                                                                                                                                                                          title="PDF to JPG"
                                                                                                                                                                                                                description="Convert PDF pages to high-quality JPG images"
                                                                                                                                                                                                                    >
                                                                                                                                                                                                                          <div className="space-y-6">
                                                                                                                                                                                                                                  {!sourceFile ? (
                                                                                                                                                                                                                                            <DropZone
                                                                                                                                                                                                                                                        onFilesSelected={handleFileSelect}
                                                                                                                                                                                                                                                                    acceptedTypes={{ 'application/pdf': ['.pdf'] }}
                                                                                                                                                                                                                                                                                maxFiles={1}
                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                                                                            <Card>
                                                                                                                                                                                                                                                                                                                        <div className="flex items-center justify-between mb-4">
                                                                                                                                                                                                                                                                                                                                      <div>
                                                                                                                                                                                                                                                                                                                                                      <p className="font-medium text-gray-900 dark:text-white">
                                                                                                                                                                                                                                                                                                                                                                        {sourceFile.name}
                                                                                                                                                                                                                                                                                                                                                                                        </p>
                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-sm text-gray-500">
                                                                                                                                                                                                                                                                                                                                                                                                                          {(sourceFile.size / (1024 * 1024)).toFixed(2)} MB
                                                                                                                                                                                                                                                                                                                                                                                                                                          </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      variant="ghost"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      size="sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setSourceFile(null);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          setImages([]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Change File
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {images.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="font-semibold text-gray-900 dark:text-white mb-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Converted Images ({images.length} page{images.length !== 1 ? 's' : ''})
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {images.map((blob, i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div key={i} className="text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <img
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            src={URL.createObjectURL(blob)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                alt={`Page ${i + 1}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    className="w-full rounded-lg mb-2 border border-gray-200 dark:border-gray-700"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="text-xs text-gray-500 mb-2">Page {i + 1}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              variant="ghost"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  size="sm"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => handleDownload(blob, i)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          icon={<Download className="w-3 h-3" />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Download
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {images.length > 1 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      variant="secondary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={handleDownloadAll}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      icon={<Download className="w-5 h-5" />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="mt-4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Download All
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Card>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {isProcessing && <ProgressBar indeterminate label="Converting PDF to images..." />}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {sourceFile && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="flex justify-end">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onClick={handleConvert}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  disabled={isProcessing}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                loading={isProcessing}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              icon={<FileImage className="w-5 h-5" />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Convert to JPG
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </ToolLayout>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }